---
#
# defaults file for zeek. override in vars, {host|group}_vars, etc

# track the version of entire suite
#
zeeksuite_version: 0.0.3

# Install zeek here
#
zeek_base: /opt/zeek

# download zeek source code from this url
#
zeek_repo_url: https://github.com/zeek/zeek

# set the branch to build from
#
# latest stable version as of time of writing: 'release/3.0'
zeek_repo_branch: release/3.0

# use this user to chown the installed source
#
zeek_user: zeek

# Zeek can use GeoIP data; including where to find it
#
zeek_geoip: true
zeek_geoip_db_url: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

# This interface will be listened to
#
zeek_interface: enp0s3

# cidrs used in the networks.cfg zeek configuration file
#
zeek_cidrs:
  - 192.168.1.0/24
  - 10.0.2.0/24

# ansible will copy and install zeek custom scripts
#
zeek_custom_scripts:
  - scripts/smb_psexec.zeek

# add/remove additional packages here
#
zkg_install_packages: [
  'zeek/j-gras/bro-af_packet-plugin',
  #  TODO: this is causing zeek to not start; removing for now 
  #  'zeek/salesforce/ja3',
  'zeek/salesforce/hassh',
]

# send mail to
#
zeek_mail_to: mail@mailto.com

# set the timezone of the VM
#
timezone: US/Pacific

# run with the a basic configuration
#
# choose false enable clustering
#
zeek_cluster: true


# number of processes used by PCAP workers
#
lb_procs: 1

# options used by PF_RING
#
enable_pfring: false

# customize PF_RING source URL here
#
pfring_repo_url: https://github.com/ntop/PF_RING.git

# The branch to check out
#
pfring_version: 7.4.0-stable
